cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path("increase-quantity/<pk>", views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path("decrease-quantity/<pk>", views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path("remove-from-cart/<pk>", views.RemoveFromView.as_view(), name='remove-from-cart'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path("payment/", views.PaymentView.as_view(), name='payment'),
]

ecom/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/', include('cart.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.shortcuts import reverse



User = get_user_model()

#checkout( addresses)
class Address(models.Model):
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'shipping'),
    )


    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=150)
    address_line_2 = models.CharField(max_length=150)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address_line_1}, {self.address_line_2}, {self.city}, {self.zip_code}"

    class Meta:
        verbose_name_plural = 'Addresses'   

#colour
class ColourVariation(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
#size
class SizeVariation(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


####product list view
class Product(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='product_images')
    description = models.TextField()
    price = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    active = models.BooleanField(default=False)
    available_colours = models.ManyToManyField(ColourVariation)
    available_sizes = models.ManyToManyField(SizeVariation)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("cart:product-detail", kwargs={'slug': self.slug}) 

    def get_price(self):
        return "{:.2f}".format(self.price / 100)


# product detail view  (add the item to cart)  
class OrderItem(models.Model):
    order = models.ForeignKey(
        "Order", related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    colour = models.ForeignKey(ColourVariation, on_delete=models.CASCADE)
    size = models.ForeignKey(SizeVariation, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    def get_raw_total_item_price(self): 
        return self.quantity * self.product.price  

    def get_total_item_price(self): 
        price =self.get_raw_total_item_price()
        return "{:.2f}".format(price / 100)

    def get_raw_subtotal(self):
        total=0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()

        

#Cart view (all the item in our cart)
class Order(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)

    billing_address = models.ForeignKey(Address, related_name='billing_address', blank=True, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(Address, related_name='shipping_address', blank=True, null=True, on_delete=models.SET_NULL)
    
    
    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"

    def get_raw_subtotal(self):
        total=0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
        return total    
    
    def get_subtotal(self):
        subtotal = self.get_raw_subtotal()
        return "{:.2f}".format(subtotal / 100)
    #total
    def get_raw_total(self):
        subtotal = self.get_raw_subtotal()
        # add tax, add delivery, substract discounts
        # total = substract-discount + tax + delivery
        return subtotal
    
    def get_total(self):
        total = self.get_raw_total()
        return "{:.2f}".format(total / 100)

#payments
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='payments')
    payment_method = models.CharField(max_length=20, choices=(('PayPal', 'PayPal'),))
    timestamp = models.DateTimeField(default=False)
    successful = models.FloatField()
    amount = models.FloatField()
    raw_response = models.TextField()

    def __str__(self):
        return self.reference_number
    
    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"    


def pre_save_product_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)

pre_save.connect(pre_save_product_reciever, sender=Product)

cart/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import (
    OrderItem, ColourVariation, Product, SizeVariation,
    Address
)

User = get_user_model()

class AddToCartForm(forms.ModelForm):
    colour = forms.ModelChoiceField(queryset=ColourVariation.objects.none())
    size = forms.ModelChoiceField(queryset=SizeVariation.objects.none())


    class Meta:
        model = OrderItem
        fields = ['quantity', 'colour', 'size']


    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=product_id)
        super().__init__(*args, **kwargs)

        self.fields['colour'].queryset = product.available_colours.all()
        self.fields['size'].queryset = product.available_sizes.all()

        
class AddressForm(forms.Form):
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)


    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )
    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )



    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )
        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs
    

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Please fill in this field")
                
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2", "Please fill in this field")
                
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field")
                
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")
                
        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1", "Please fill in this field")
                
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2", "Please fill in this field")
                
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field")
                
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")
                    

            

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views import generic
from .forms import AddToCartForm, AddressForm
from .models import Product, OrderItem, Address
from .utils import get_or_set_order_session
# Create your views here.

class ProductListView(generic.ListView):
    template_name = 'cart/product_list.html'
    queryset = Product.objects.all()


class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    
    form_class = AddToCartForm
    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse('cart:summary')  #TODO: CART

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs  

    def form_valid(self, form):
        order= get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            colour= form.cleaned_data['colour'],
            size= form.cleaned_data['size'],
            )
        if item_filter.exists():
            item = item_filter.first()
            item.quantity = int(form.cleaned_data['quantity'])
            item.save()
        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)
           
    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()

        return context 


class CartView(generic.TemplateView):
   template_name = "cart/cart.html"
   def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)

        return context 


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")



class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <=1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:summary")    


class RemoveFromView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        
        
        return redirect("cart:summary")


class CheckoutView(generic.FormView):
    template_name = "cart/checkout.html"
    form_class = AddressForm

        
    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get(
            'selected_shipping_address')
        selected_billing_address = form.cleaned_data.get(
            'selected_billing_address')
        
        if selected_shipping_address:
            order.shipping_address =selected_shipping_address
        else:
            address = Address.objects.create(
                address_type= 'S',
                user= self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address == address
        

        if selected_billing_address:
            order.billing_address =selected_billing_address
        else:
            address = Address.objects.create(
                address_type= 'B',
                user= self.request.user,
                address_line_1=form.cleaned_data['billing_address_line_1'],
                address_line_2=form.cleaned_data['billing_address_line_2'],
                zip_code=form.cleaned_data['billing_zip_code'],
                city=form.cleaned_data['billing_city'],
            )
            order.billing_address == address
        order.save()


        messages.info(self.request, "You have successfully added addresses.")    
        return super(CheckoutView, self).form_valid(form)
        
    def get_success_url(self):
        return reverse("cart:payment") 

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)

        return context      

class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID

        return context  
        

templates/cart/cart.html
{% extends "base.html" %} {% block content %}

<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0">
        <a href="{% url 'home' %}">Home</a>
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black">Cart</strong>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5">
      <div class="col-md-12">
        <div class="site-blocks-table">
          <table>
            <thead>
              <tr>
                <th>Image</th>
                <th>product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order.items.all %}
              <tr>
                <td class="product-thumbnail">
                  <img src="{{ item.product.image.url }}" class="img-fluid" />
                </td>
                <td class="product-name">
                  <h2 class="h5 text-black">{{ item.product.title }}</h2>
                  <small>Size: {{ item.size.name }}</small>
                  <small>Colour: {{ item.colour.name }}</small>
                </td>
                <td>${{ item.product.get_price }}</td>

                <td>
                  <div class="input-group" style="max-width: 120px">
                    <div class="input-group-prepend">
                      <a
                        href="{% url 'cart:decrease-quantity' item.id %}"
                        type="button"
                        class="btn btn-outline-primary btn-sm"
                      >
                        &minus;
                      </a>
                    </div>
                    <input
                      type="text"
                      class="form-control text-center"
                      value="{{ item.quantity }}"
                    />
                    <div class="input-group-append">
                      <a
                        href="{% url 'cart:increase-quantity' item.id %}"
                        type="button"
                        class="btn btn-outline-primary btn-sm"
                      >
                        &plus;
                      </a>
                    </div>
                  </div>
                </td>

                <td>${{ item.get_total_item_price }}</td>
                <td>
                  <a
                    href="{% url 'cart:remove-from-cart' item.id %}"
                    class="btn btn-primary btn-sm"
                    >X</a
                  >
                </td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="6">
                  There are no items in your cart.
                  <a href="{% url 'cart:product-list'%}"> Continue shopping</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5"></div>
    {% if order.items.count > 0 %}
    <div class="row">

      <div class="col-md-6">
        <div class="row mb-5">
          <div class="col-md-12">
            <a
              class="btn btn-outline-primary btn-sm btn-block"
              href="{% url 'cart:product-list' %}"
              >Continue shopping</a
            >
          </div>
        </div>
      </div>

      <div class="col-md-6 pl-5">
         <div class="row justify-content-end">
          <div class="col-md-12">

            <div class="row">
              <div class="col-md-12 text-right border-bottom mb-5">
                <h3 class="text-black h4 text-uppercase"> Cart Total</h3>
              </div>
            </div>

            <div class="row mb-5 justify-content-between d-flex">
              <div class="col-md-6">
                <strong class="text-black">Subtotal</strong>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">${{ order.get_subtotal }}</strong>
              </div>
            </div>
            <div class="row mb-5 justify-content-between d-flex">
              <div class="col-md-6">
                <strong class="text-black">Total</strong>
              </div>
              <div class="col-md-6 text-right">
                <strong class="text-black">${{ order.get_total}}</strong>
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-12">
                <a class="btn btn-primary btn-lg py-3 btn-block" href="{% url 'cart:checkout' %}">Proceed to  checkout</a>
              </div>
            </div>

          </div>
         </div>
      </div>


    </div>
    {% endif %}
  </div>
</div>

{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="bg-light py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12 mb-0">
          <a href="{% url 'home' %}">Home</a><span class="mx-2 mb-0">/</span>
          <a href="{% url 'cart:summary' %}" class="text-black">Cart</a><span class="mx-2 mb-0">/</span>
          <strong class="text-black">Checkout</strong>
        </div>
      </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
      

            {% if not request.user.is_authenticated %}
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="border p-4 rounded" role="alert">
                        You are nearly finished with you order.
                        To finalize yout order, please <a>Login</a> or <a>Singup</a>.
                    </div>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuemin="0" aria-valuemax="100%">
                        90% complete</div>
            
                    </div>
            
                </div>
            </div>

            {% else %}
            <form method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mb-5 mb-md-0">
                        <h2 class="h3 mb-3 text-black text-center">
                            Billing Details
                        </h2>
                        <hr />
                        <div class="p-2 p-lg-2">
                            {{ form|crispy }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg py-3 btn-block">Proceed to payment</button>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="row mb-5">
                            <div class="col-md-12">
                                <h2 class="h3 mb-3 text-black text-center">Your Order</h2>
                                <hr>
                                <div class="p-3 p-lg-5">
                                    <table class="table site-block-order-table mb-5">

                                        <thead>
                                            <th>product</th>
                                            <th>Total</th>
                                        </thead>

                                        <tbody>
                                          {% for item in order.items.all %}
                                          <tr>
                                            <td >
                                                {{ item.size.name }}, {{ item.colour.name }}, {{ item.product.title }}
                                                <strong class="mx-2">X </strong>{{ item.quantity }}
                                            </td>
                                            <td>
                                                ${{ item.get_total_item_price }}
                                            </td>
                                          </tr>
                                          {% empty %}
                                          <tr>
                                            <td colspan="6">
                                              There are no items in your cart.
                                              <a href="{% url 'cart:product-list'%}"> Continue shopping</a>
                                            </td>
                                          </tr>
                                          {% endfor %}
                                          <tr>
                                            <td><strong>Subtotal</strong></td>
                                            <td>${{ order.get_subtotal }}</td>
                                          </tr>
                                          <tr>
                                            <td><strong class="strong text-black font-weight-bold">Total</strong></td>
                                            <td><strong class="strong text-black font-weight-bold">${{ order.get_total }}</strong></td>
                                          </tr>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </form>
            {% endif %}

      </div>
    </div>
</div>
  




{% endblock content %}

templates/cart/payment.html
{% extends "base.html" %}

{% block content %}


<div class="col-md-12">
    <div id="paypal-button-container">
    </div>
</div>

{% endblock content %}




{% block scripts %}
<script src="https://www.paypal.com/sdk/js?client-id=PAYPAL_CLIENT_ID"></script>
<script>
    const FUNDING_SOURCES = [
      // EDIT FUNDING SOURCES
        paypal.FUNDING.PAYPAL,
        paypal.FUNDING.PAYLATER,
        paypal.FUNDING.VENMO,
        paypal.FUNDING.CARD
    ];
    FUNDING_SOURCES.forEach(fundingSource => {
      paypal.Buttons({
        fundingSource,

        style: {
          layout: 'vertical',
          shape: 'rect',
          color: (fundingSource == paypal.FUNDING.PAYLATER) ? 'gold' : '',
        },

        createOrder: async (data, actions) => {
          try {
            const response = await fetch("http://localhost:9597/orders", {
              method: "POST"
            });

            const details = await response.json();
            return details.id;
          } catch (error) {
            console.error(error);
            // Handle the error or display an appropriate error message to the user
          }
        },

        

        onApprove: async (data, actions) => {
          try {
            const response = await fetch(`http://localhost:9597/orders/${data.orderID}/capture`, {
              method: "POST"
            });

            const details = await response.json();
            // Three cases to handle:
            //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
            //   (2) Other non-recoverable errors -> Show a failure message
            //   (3) Successful transaction -> Show confirmation or thank you message

            // This example reads a v2/checkout/orders capture response, propagated from the server
            // You could use a different API or structure for your 'orderData'
            const errorDetail = Array.isArray(details.details) && details.details[0];

            if (errorDetail && errorDetail.issue === 'INSTRUMENT_DECLINED') {
              return actions.restart();
              // https://developer.paypal.com/docs/checkout/integration-features/funding-failure/
            }

            if (errorDetail) {
              let msg = 'Sorry, your transaction could not be processed.';
              msg += errorDetail.description ? ' ' + errorDetail.description : '';
              msg += details.debug_id ? ' (' + details.debug_id + ')' : '';
              alert(msg);
            }

            // Successful capture! For demo purposes:
            console.log('Capture result', details, JSON.stringify(details, null, 2));
            const transaction = details.purchase_units[0].payments.captures[0];
            alert('Transaction ' + transaction.status + ': ' + transaction.id + 'See console for all available details');
          } catch (error) {
            console.error(error);
            // Handle the error or display an appropriate error message to the user
          }
        },
      }).render("#paypal-button-container");
    })
  </script>
{% endblock scripts %}

templates/cart/product_detail.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% block content %}

<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0">
        <a href="{% url 'home' %}">Home</a>
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black">{{ product.title}}</strong>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5">
    
      <div class="col-md-6">
        <img src="{{ product.image.url }}" class="img-fluid" />
      </div>


      <div class="col-md-6">
        <h2 class="text-black">{{ product.title }}</h2>
        <p>{{ product.description }}</p>
        <form method="POST">
          {% csrf_token %} {{ form|crispy }}
          <button type="submit" class="btn btn-sm btn-primary buy-now">
            Add to cart
          </button>
        </form>
      </div>


    </div>
  </div>
</div>

{% endblock content %}

templates/cart/product_list.html
{% extends "base.html" %} {% block content %}

<div class="bg-light py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12 mb-0">
        <a href="{% url 'home' %}">Home</a>
        <span class="mx-2 mb-0">/</span>
        <strong class="text-black">Shop</strong>
      </div>
    </div>
  </div>
</div>

<div class="site-section">
  <div class="container">
    <div class="row mb-5">
      
        {% for product in object_list %}
        <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <figure class="block-4-image">
                <a href="{{ product.get_absolute_url}}">
                    <img src="{{ product.image.url }}" class="img-fluid">
                </a>
              </figure>
            <div class="block-4-text p-4">
                <a href="{{ product.get_absolute_url}}">
                    <h3>{{ product.title }}</h3>
                </a>
                <p class="mb-0" >{{ product.description}}</p>
            </div>
        </div>

        {% endfor %}
      
    </div>
  </div>
</div>

{% endblock content %}